language: node_js
node_js:
  - "8.4"
sudo: required
cache:
  directories:
    - $HOME/.npm
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
script:
  - npm i react-native-cli -g
  - react-native bundle --dev false --entry-file index.ios.js --bundle-output ios/main.jsbundle --platform ios
matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      sudo: required
      node_js: false
      before_install:
        - nvm install 8.9.3
        - nvm use 8.9.3
        - node --version
        # install NDK
        - openssl aes-256-cbc -K $encrypted_e28d423744bc_key -iv $encrypted_e28d423744bc_iv -in env.json.enc -out env.json -d
        - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
        - export ANDROID_NDK_HOME=$HOME/android-ndk-root
        - echo "y" | sdkmanager "cmake;3.6.4111459"
        - npm install -g yarn@1.3.2
      install:
        - travis_retry yarn
        - npm t
      android:
        components:
          - tools
          - platform-tools
          - build-tools-23.0.1
          - build-tools-23.0.3
          - build-tools-25.0.1
          - build-tools-25.0.3
          - android-23
          - android-25
          - android-27
          - extra
          - extra-android-m2repository
          - extra-android-support
          - extra-google-google_play_services
          - extra-google-m2repository
          - addon-google_apis-google-16
          - cmake
        licenses:
          - '.+'
      script:
        - cd android && ./gradlew assembleDebug && ./gradlew assembleRelease
    - language: objective-c
      os: osx
      osx_image: xcode9.2
      node_js: false
      before_install:
        - nvm install 8.9.3
        - nvm use 8.9.3
        - node --version
        - openssl aes-256-cbc -K $encrypted_e28d423744bc_key -iv $encrypted_e28d423744bc_iv -in env.json.enc -out env.json -d
        - npm install -g yarn@1.3.2
      install:
        - travis_retry gem install xcpretty
        - travis_wait yarn
      xcode_project: ios/edge.xcworkspace
      xcode_scheme: ios/edge
      script:
        - cd ios
        - xcodebuild -derivedDataPath build clean build -scheme edge -configuration release -sdk iphonesimulator11.2 CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""
